### ISSUE TITLE
Choose a rooter

### ISSUE THREAD

**Issue by guijesuis** [totorototo/strava#3]
we have have to remove react router flux. We can use
- react navigation
- react  router v4

**Comment by totorototo** [comment]
c'est pas faux!

**Comment by totorototo** [comment]
React navigation will be evaluated first. 
Implementation in progress. Still some issues using deeplinking provided by react-navigation.

**Comment by totorototo** [comment]
navigation works fine,
deep linking implemented. 
Case closed.
