### ISSUE TITLE
 Continus integration

### ISSUE THREAD

**Issue by guijesuis** [totorototo/strava#5]
chose and set up CI
- https://github.com/integrations/feature/continuous-integration
- travis https://travis-ci.org/ ??
- biterise ?? http://blog.thebakery.io/continuous-integration-for-react-native-applications-with-fastlane-and-bitrise-ios-version/ 
- others ...

**Comment by totorototo** [comment]
work in progress.
Bitrise was actually chosen. 
Android and pipelines were set up. 
Still need to sign, deploy and publish artifacts. 

fastlane? dunno yet.

**Comment by totorototo** [comment]
Android: Job done. Bitrise pipeline done. (revision number to be set correctly.
Ios: need a paid developer account.
