### ISSUE TITLE
Android application crash at startup - Production

### ISSUE THREAD

**Issue by totorototo** [totorototo/strava#70]
Issue while testing the release build of the application.
Got the same behavior on physical device. 

Here is the stack trace:

> 10-26 21:52:25.764  8656  8678 E AndroidRuntime: Process: com.lybitos, PID: 8656
10-26 21:52:25.764  8656  8678 E AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'u.View.propTypes.style'), stack:
10-26 21:52:25.764  8656  8678 E AndroidRuntime: <unknown>@687:1062
10-26 21:52:25.764  8656  8678 E AndroidRuntime: i@2:565
10-26 21:52:25.764  8656  8678 E AndroidRuntime: n@2:348
10-26 21:52:25.764  8656  8678 E AndroidRuntime: t@2:210
10-26 21:52:25.764  8656  8678 E AndroidRuntime: <unknown>@686:251
10-26 21:52:25.764  8656  8678 E AndroidRuntime: i@2:565
10-26 21:52:25.764  8656  8678 E AndroidRuntime: n@2:348
10-26 21:52:25.764  8656  8678 E AndroidRuntime: t@2:210
10-26 21:52:25.764  8656  8678 E AndroidRuntime: <unknown>@408:292
10-26 21:52:25.764  8656  8678 E AndroidRuntime: i@2:565
10-26 21:52:25.764  8656  8678 E AndroidRuntime: n@2:348
10-26 21:52:25.764  8656  8678 E AndroidRuntime: t@2:210
10-26 21:52:25.764  8656  8678 E AndroidRuntime: <unknown>@344:253
10-26 21:52:25.764  8656  8678 E AndroidRuntime: i@2:565
10-26 21:52:25.764  8656  8678 E AndroidRuntime: n@2:348
10-26 21:52:25.764  8656  8678 E AndroidRuntime: t@2:210
10-26 21:52:25.764  8656  8678 E AndroidRuntime: <unknown>@303:143
10-26 21:52:25.764  8656  8678 E AndroidRuntime: i@2:565
10-26 21:52:25.764  8656  8678 E AndroidRuntime: n@2:348
10-26 21:52:25.764  8656  8678 E AndroidRuntime: t@2:210
10-26 21:52:25.764  8656  8678 E AndroidRuntime: <unknown>@12:38
10-26 21:52:25.764  8656  8678 E AndroidRuntime: i@2:565
10-26 21:52:25.764  8656  8678 E AndroidRuntime: n@2:278
10-26 21:52:25.764  8656  8678 E AndroidRuntime: t@2:210
10-26 21:52:25.764  8656  8678 E AndroidRuntime: global code@1013:9
10-26 21:52:25.764  8656  8678 E AndroidRuntime: 
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
10-26 21:52:25.764  8656  8678 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
10-26 21:52:25.845  1671  2158 W ActivityManager:   Force finishing activity com.lybitos/.MainActivity
10-26 21:52:25.858  1304  1304 W SurfaceFlinger: couldn't log to binary event log: overflow.
10-26 21:52:25.881  8656  8673 D EGL_emulation: eglMakeCurrent: 0xa07469a0: ver 2 0 (tinfo 0xa077d8d0)
10-26 21:52:25.975  1671  1877 W InputMethodManagerService: Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@11db04d (uid=10091 pid=8656)
10-26 21:52:25.982  1671  5510 I OpenGLRenderer: Initialized EGL, version 1.4
10-26 21:52:25.982  1671  5510 D OpenGLRenderer: Swap behavior 1
10-26 21:52:25.983  1671  5510 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
10-26 21:52:25.983  1671  5510 D OpenGLRenderer: Swap behavior 0
10-26 21:52:25.987  1671  1684 I WindowManager: Failed to capture screenshot of Token{a568e ActivityRecord{e9e2689 u0 com.lybitos/.MainActivity t24 f}} appWin=Window{96e92ec u0 com.lybitos/com.lybitos.MainActivity} drawState=4

After having looking for the root cause for few minutes, it seems the issue comes from: 

> Card.propTypes = {
  children: PropTypes.any,
  flexDirection: PropTypes.string,
  containerStyle: ViewPropTypes.style,
  wrapperStyle: ViewPropTypes.style,
  overlayStyle: ViewPropTypes.style,
  title: PropTypes.string,
  titleStyle: NativeText.propTypes.style,
  featuredTitle: PropTypes.string,
  featuredTitleStyle: Text.propTypes.style,
  featuredSubtitle: PropTypes.string,
  featuredSubtitleStyle: Text.propTypes.style,
  dividerStyle: ViewPropTypes.style,
  image: Image.propTypes.source,
  imageStyle: ViewPropTypes.style,
  imageWrapperStyle: ViewPropTypes.style,
  fontFamily: PropTypes.string,
};

> import { View, ViewPropTypes as RNViewPropTypes } from 'react-native';
const ViewPropTypes = RNViewPropTypes || View.propTypes;
export default ViewPropTypes;

**Comment by totorototo** [comment]
[https://github.com/react-native-training/react-native-elements/issues/670](url)

**Comment by totorototo** [comment]
#https://github.com/react-native-training/react-native-elements/issues/670

**Comment by YeshanJay** [comment]
https://github.com/facebook/react-native/issues/16567

**Comment by totorototo** [comment]
dependency update + remove faulty component. (countdown).
